version: '3.9'
services:
    server:
        build:
            context: .

        image: "esultanik/justctf-archive-polyglot"

        restart: "always"

        ports:
            - "8080:80/tcp"

        environment:
            - FLAG=${FLAG:?You must set the FLAG environment variable}
